have_header: checking for ruby/st.h... -------------------- yes

"gcc -std=gnu99 -o conftest -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC conftest.c  -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L/home/vagrant/.rbenv/versions/2.7.6/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -E -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ruby/st.h>
/* end */

--------------------

have_header: checking for st.h... -------------------- yes

"gcc -E -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC  conftest.c -o conftest.i"
In file included from conftest.c:3:0:
/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward/st.h:2:2: 警告: #warning use "ruby/st.h" instead of bare "st.h" [-Wcpp]
 #warning use "ruby/st.h" instead of bare "st.h"
  ^
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <st.h>
/* end */

--------------------

have_func: checking for rb_enc_interned_str() in ruby.h... -------------------- no

"gcc -std=gnu99 -o conftest -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC conftest.c  -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L/home/vagrant/.rbenv/versions/2.7.6/lib -lruby  -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:16:57: エラー: ‘rb_enc_interned_str’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_interned_str; return !p; }
                                                         ^
conftest.c:16:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_interned_str; return !p; }
/* end */

"gcc -std=gnu99 -o conftest -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC conftest.c  -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L/home/vagrant/.rbenv/versions/2.7.6/lib -lruby  -lm   -lc"
/tmp/ccMZs5AD.o: 関数 `t' 内:
/home/vagrant/komaki/vendor/bundle/ruby/2.7.0/gems/msgpack-1.6.0/ext/msgpack/conftest.c:17: `rb_enc_interned_str' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: extern void rb_enc_interned_str();
17: int t(void) { rb_enc_interned_str(); return 0; }
/* end */

--------------------

have_func: checking for rb_hash_new_capa() in ruby.h... -------------------- no

"gcc -std=gnu99 -o conftest -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC conftest.c  -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L/home/vagrant/.rbenv/versions/2.7.6/lib -lruby  -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:16:57: エラー: ‘rb_hash_new_capa’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_hash_new_capa; return !p; }
                                                         ^
conftest.c:16:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_hash_new_capa; return !p; }
/* end */

"gcc -std=gnu99 -o conftest -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/x86_64-linux -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0/ruby/backward -I/home/vagrant/.rbenv/versions/2.7.6/include/ruby-2.7.0 -I. -I/home/vagrant/.rbenv/versions/2.7.6/include    -g -O2 -fPIC conftest.c  -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L. -L/home/vagrant/.rbenv/versions/2.7.6/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/vagrant/.rbenv/versions/2.7.6/lib -L/home/vagrant/.rbenv/versions/2.7.6/lib -lruby  -lm   -lc"
/tmp/cc1gy5L0.o: 関数 `t' 内:
/home/vagrant/komaki/vendor/bundle/ruby/2.7.0/gems/msgpack-1.6.0/ext/msgpack/conftest.c:17: `rb_hash_new_capa' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: extern void rb_hash_new_capa();
17: int t(void) { rb_hash_new_capa(); return 0; }
/* end */

--------------------

